# Generated by Django 5.0.6 on 2024-07-05 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, choices=[('HEADACHE', 'Headache'), ('SEIZURES', 'Seizures'), ('DIABETES', 'Diabetes'), ('HYPERTENSION', 'Hypertension'), ('DEPRESSION', 'Depression'), ('PNEUMONIA', 'Pneumonia'), ('ARTHRITIS', 'Arthritis'), ('DERMATHITIS', 'Dermathitis'), ('BACK_PAIN', 'Back Pain')], default='HEADACHE', max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('CHRONIC', 'Chronic'), ('ACUTE', 'Acute')], default='ACUTE', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_diagnosis', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnosis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_facility', models.CharField(blank=True, choices=[('Korle Bu Main hospital ', 'Korle Bu Main Hospital'), ('Legon Hospital', 'Legon Hospital'), ('UG Medical center', 'Ug Medical Center'), ('Accra Medical center ', 'Accra Medical Center'), ('Noguchie Health center', 'Noguchie Health Center')], default='Korle Bu Main hospital ', max_length=255, null=True)),
                ('investigation', models.CharField(blank=True, choices=[('Blood tests  ', 'Blood Tests'), ('Urinalysis   ', 'Urinalysis'), ('Biopsy       ', 'Biopsy'), ('Amniocentesis', 'Amniocentesis'), ('Thyroid function tests', 'Thyroid Function Tests')], max_length=255, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Pathology   ', 'Pathology'), ('Cardiology  ', 'Cardiology'), ('Cardithoracy', 'Cardithoracy'), ('Gynaecology ', 'Gynaecology'), ('Pediatric   ', 'Pediatric'), ('Opthometry  ', 'Opthometry')], max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_investigation', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_investigation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(blank=True, choices=[('Paracetamol    ', 'Paracetamol'), ('Lacosamide     ', 'Lacosamide'), ('Metformin      ', 'Metformin'), ('ACE_inhibitors ', 'Ace Inhibitors'), ('SSR_inhibitors ', 'Ssr Inhibitors'), ('Amoxicillin    ', 'Amoxicillin'), ('Azathioprines  ', 'Azathioprines'), ('Hydrocortisones', 'Hydrocortisones'), ('Ibuprofen      ', 'Ibuprofen'), ('Doxycycline    ', 'Doxycycline')], max_length=255, null=True)),
                ('dose', models.CharField(blank=True, choices=[('OD ', 'Od'), ('BID', 'Bid'), ('TID', 'Tid'), ('QID', 'Qid')], max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=30, null=True)),
                ('strength', models.CharField(blank=True, choices=[('50mg ', 'Mg'), ('100mg', 'M G'), ('200mg', 'Mg'), ('500mg', 'M G')], max_length=30, null=True)),
                ('quatity', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicals.diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescription', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
