# Generated by Django 5.0.6 on 2024-07-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0002_rename_quatity_prescription_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Once Daily', 'Once Daily'), ('Two Times Daily', 'Twice Daily'), ('Three Times Daily', 'Thrice Daily'), ('Four Times Daily', 'Quadrice Daily')], default='Once Daily', max_length=255, null=True),
        ),
    ]
