# Generated by Django 5.0.6 on 2024-07-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0004_alter_diagnosis_diagnosis_alter_diagnosis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='investigation',
            field=models.CharField(blank=True, choices=[('Blood tests', 'Blood Tests'), ('Urinalysis', 'Urinalysis'), ('Biopsy', 'Biopsy'), ('Amniocentesis', 'Amniocentesis'), ('Thyroid function tests', 'Thyroid Function Tests')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='unit',
            field=models.CharField(blank=True, choices=[('Pathology', 'Pathology'), ('Cardiology', 'Cardiology'), ('Cardithoracy', 'Cardithoracy'), ('Gynaecology', 'Gynaecology'), ('Pediatric', 'Pediatric'), ('Opthometry', 'Opthometry')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(blank=True, choices=[('Paracetamol', 'Paracetamol'), ('Lacosamide', 'Lacosamide'), ('Metformin', 'Metformin'), ('ACE inhibitors', 'Ace Inhibitors'), ('SSR inhibitors', 'Ssr Inhibitors'), ('Amoxicillin', 'Amoxicillin'), ('Azathioprines', 'Azathioprines'), ('Hydrocortisones', 'Hydrocortisones'), ('Ibuprofen', 'Ibuprofen'), ('Doxycycline', 'Doxycycline')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='strength',
            field=models.CharField(blank=True, choices=[('50mg', 'Mg'), ('100mg', 'M G'), ('200mg', 'Mg'), ('500mg', 'M G')], max_length=30, null=True),
        ),
    ]
