# Generated by Django 5.0.6 on 2024-07-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0005_alter_investigation_investigation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='date',
            field=models.DateField(auto_now_add=True, default='2023-05-12'),
            preserve_default=False,
        ),
    ]
