# Generated by Django 5.0.6 on 2024-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0006_alter_investigation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='referral_facility',
            field=models.CharField(blank=True, choices=[('Korle Bu Main hospital', 'Korle Bu Main Hospital'), ('Legon Hospital', 'Legon Hospital'), ('UG Medical center', 'Ug Medical Center'), ('Accra Medical center', 'Accra Medical Center'), ('Noguchie Health center', 'Noguchie Health Center')], default='Korle Bu Main hospital', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dose',
            field=models.CharField(blank=True, choices=[('OD', 'Od'), ('BID', 'Bid'), ('TID', 'Tid'), ('QID', 'Qid')], max_length=255, null=True),
        ),
    ]
