# Generated by Django 5.0.6 on 2024-07-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0007_alter_investigation_referral_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Once Daily', 'Once Daily'), ('Two Times Daily', 'Two Times Daily'), ('Three Times Daily', 'Three Times Daily'), ('Four Times Daily', 'Four Times Daily')], default='Once Daily', max_length=255, null=True),
        ),
    ]
