# Generated by Django 5.0.6 on 2024-08-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0009_alter_prescription_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='diagnosis',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='patient_disease', to='medicals.diagnosis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnosis', to='medicals.diagnosis'),
        ),
    ]
