# Generated by Django 5.0.6 on 2024-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0010_investigation_diagnosis_alter_prescription_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.CharField(blank=True, choices=[('Headache', 'Headache'), ('Seizures', 'Seizures'), ('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('Malaria', 'Malaria'), ('Depression', 'Depression'), ('Pneumonia', 'Pneumonia'), ('Arthritis', 'Arthritis'), ('Dermathitis', 'Dermathitis'), ('Back Pain', 'Back Pain')], default='Headache', max_length=20, null=True),
        ),
    ]
