# Generated by Django 5.0.6 on 2024-06-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientVitals',
            new_name='PatientVital',
        ),
    ]
