# Generated by Django 5.0.6 on 2024-06-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_patientvitals_patientvital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvital',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patientvital',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
