# Generated by Django 5.0.6 on 2024-06-02 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_patientvital_patient_id_patientvital_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvital',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientvital',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
