# Generated by Django 5.0.6 on 2024-06-05 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_patientvital_patient_patientvital_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('triage', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('SEVERE', 'Severe'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20, null=True)),
                ('comments', models.TextField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientVital',
        ),
    ]
