# Generated by Django 5.0.6 on 2024-06-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='type',
            field=models.CharField(blank=True, choices=[('In Person', 'In Person'), ('Virtual', 'Virtual')], max_length=20, null=True),
        ),
    ]
