# Generated by Django 5.0.6 on 2024-06-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_availability_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='doctor',
        ),
    ]
