# Generated by Django 5.0.6 on 2024-06-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookPatient',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
