# Generated by Django 5.0.6 on 2024-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_appointment_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='triage',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('SEVERE', 'Severe'), ('NORMAL', 'Normal')], max_length=20, null=True),
        ),
    ]
