# Generated by Django 5.0.6 on 2024-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIAN', 'Christian'), ('ISLAM', 'Islam')], default='CHRISTIAN', max_length=255, null=True),
        ),
    ]
