# Generated by Django 5.0.6 on 2024-06-16 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profilemodel_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
