# Generated by Django 5.0.6 on 2024-08-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profilemodel_profile_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
