# Generated by Django 5.0.6 on 2024-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpatient',
            name='triage',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('SEVERE', 'Severe'), ('NORMAL', 'Normal')], max_length=20, null=True),
        ),
    ]
