# Generated by Django 5.0.6 on 2024-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_bookpatient_triage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpatient',
            name='triage',
            field=models.CharField(blank=True, choices=[('SELECT', 'Slelect'), ('CRITICAL', 'Critical'), ('SEVERE', 'Severe'), ('NORMAL', 'Normal')], max_length=20, null=True),
        ),
    ]
