# Generated by Django 5.0.6 on 2024-06-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_availability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
