# Generated by Django 5.0.6 on 2024-06-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_availability_day_alter_availability_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
    ]
