# Generated by Django 5.0.6 on 2024-08-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_created_at_appointment_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='patient',
        ),
    ]
